### ISSUE TITLE
Allow non-CSHers to develop without ties to CSH

### ISSUE THREAD

**Issue by MoralCode** [wilsonmcdade/tunnelvision#9]
This is similar to my issue on the ScheduleMaker repo https://github.com/ComputerScienceHouse/schedulemaker/issues/320

I notice the README includes this:
> (Reach out to a maintainer of this repo for credentials for the dev database)

However I think it might be better to include instructions in the repo to allow people to set up a dev database without needing permission from CSH or a CSHer, such as by either:

- Including instructions to initialize a blank database for devs to populate their own sample data
    - ideally: also include a script to load some sample data
- Include a download link or instructions for where to acquire a database dump of the dev database 

With all that said, realistically I'm not planning to contribute, so this is just a low priority issue to hopefully help make this project more friendly to the (growing) FOSS community at RIT who i imagine might like to contribute to this project once it hits a production state.

**Comment by wilsonmcdade** [comment]
@humannum14916 has an open PR to add SQLAlchemy as an ORM, meaning people can use their own database to develop. That was the biggest hangup because devs need the CSH VPN in order to connect to our postgresql instance. The next issue is that most people don't have access to an S3 instance but that's something you don't need access to the VPN for, and we can give out credentials for our development S3 bucket.
